#pragma config(UserModel, "C:/Users/’≈÷Æ––/Desktop/VEXNothingButNet/MSConfig.h")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "UserConfig.h"
#include "CompetitionUtil.h"

#include "Init.c"
#include "Autonomous.c"
#include "UserControl.c"
